jobs:
  include:
    - language: csharp
      mono: none
      dist: xenial
      env: TEA_UTIL_ENV="csharp"
    - language: go
      go: 1.12.x
      install: 
        - export GO111MODULE=on
      env: TEA_UTIL_ENV="go"
    - language: go
      go: 1.13.x
      env: TEA_UTIL_ENV="go"
      install:
        - export GO111MODULE=on
    - language: go
      go: 1.14.x
      env: TEA_UTIL_ENV="go"
      install:
        - export GO111MODULE=on
    - language: go
      go: 1.15.x
      env: TEA_UTIL_ENV="go"
      install:
        - export GO111MODULE=on  
    - language: php
      php: '5.6'
      env: TEA_UTIL_ENV="php"
    - language: php
      php: '7.0'
      env: TEA_UTIL_ENV="php"
    - language: php
      php: '7.1'
      env: TEA_UTIL_ENV="php"
    - language: php
      php: '7.2'
      env: TEA_UTIL_ENV="php"
    - language: php
      php: '7.3'
      env: TEA_UTIL_ENV="php"
    - language: python
      python: 3.4
      env: TEA_UTIL_ENV="python"
    - language: python
      python: 3.5
      env: TEA_UTIL_ENV="python"
    - language: python
      python: 3.6
      env: TEA_UTIL_ENV="python"
    - language: python
      python: 3.7
      env: TEA_UTIL_ENV="python"
    - language: python
      python: 3.8
      env: TEA_UTIL_ENV="python"


script:
  - bash ut.sh ${TEA_UTIL_ENV}
